# Site config
title: A day in my life 
description: All kind of interesting stuff will be published here 

# Serving
# detach              : false
# port                : 4000
host                : 172.17.199.134
# baseurl             : "" # does not include hostname
# show_dir_listing    : false

# Jekyll configuration
markdown: kramdown
theme: jekyll-theme-leap-day
