# Serving
# detach              : false
# port                : 4000
host                : 172.17.199.134
# baseurl             : "" # does not include hostname
# show_dir_listing    : false

# Jekyll configuration
markdown: kramdown
