# Site wide configuration

title: "mrBussy.eu"
locale: "en_US"
#url:		  http://localhost:4000 #https://mrbussy.github.io
url:		  https://mrbussy.github.io
url:      http://www.mrbussy.eu


# Jekyll configuration

# The release of Jekyll Now that you're using
version: v1.2.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Rudi Middel 
  avatar: https://avatars3.githubusercontent.com/u/1843912?v=3&s=460
  bio: "A curious person."
  email: r.middel@mrbussy.eu
  disqus-shortname:
  twitter: mrBussy #username
  facebook: rudi-middel #username
  google:
    plus: rudimiddel #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: mrBussy 
  stackoverflow: 3899563/rudi-middel #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: rudimiddel #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
  
# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
