# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: My simple blogging site
email: blog@mrbussy.eu
description: >- # this means to ignore newlines until "baseurl:"
     This site will contain all kind of random thoughts. I will try to categorise them to keep some kind of order.
     I also will try to regular post some updates, but I find it hard to keep track on the things to post. And finally, I will try to use a good git flow (which I just realised I do not for the start of this site :()
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.mrbussy.eu" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mrbussy

# Build settings
markdown: GFM #kramdown
#theme: minima
#theme: no-style-please
theme: jekyll-theme-console

highlighter: rouge

#theme_config:
#  appearance: "auto"
#  back_home_text: ".." # customize text for homepage link in post layout
#  date_format: "%Y-%m-%d" # customize how date is formatted
#  show_description: false # show blog description in home page

#https://github.com/b2a3e8/jekyll-theme-console/blob/master/404.md
# https://github.com/b2a3e8/jekyll-theme-console
header_pages:
  - index.md
  - about.md
  - archive.md
  - search.md

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true

footer: 'follow us on <a href="https://twitter.com/xxx">twitter</a>'

google_analytics: UA-NNNNNNNN-N

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
